"""
BizLens v2.3.2 — Deployment & Ecosystem Module
"""

import subprocess
import sys
import time
from pathlib import Path
from rich.console import Console
from rich.table import Table
from . import ENABLE_PROFILING
from .utils import to_pandas

console = Console()


class deploy:
    """
    Deploy BizLens analytics as interactive web applications.
    """

    @staticmethod
    def streamlit_app(data=None, title: str = "BizLens Analytics Dashboard",
                      port: int = 8501, launch: bool = True,
                      save_path: str = "bizlens_dashboard.py", show_timing: bool = False):
        if ENABLE_PROFILING or show_timing:
            start = time.perf_counter()

        if data is not None:
            data = to_pandas(data)

        app_code = f'''"""
BizLens Analytics Dashboard — Generated by BizLens v2.2.16
"""

import streamlit as st
import pandas as pd
import bizlens as bl

st.set_page_config(page_title="{title}", page_icon="📊", layout="wide")

st.title("📊 {title}")
st.markdown("**Powered by BizLens v2.2.16**")

if st.sidebar.button("Load Sample Data"):
    df = bl.load_dataset("tips")
    st.session_state.df = df

if 'df' in st.session_state:
    df = st.session_state.df
    st.dataframe(df.head())
    st.metric("Rows", len(df))
    st.metric("Columns", len(df.columns))
else:
    st.info("👈 Use sidebar to load data")
'''

        Path(save_path).write_text(app_code)
        console.print(f"[green]✅ Streamlit app saved to: {save_path}[/green]")

        if launch:
            try:
                subprocess.Popen([sys.executable, "-m", "streamlit", "run", save_path, "--server.port", str(port)])
                console.print(f"[green]🚀 Dashboard running at http://localhost:{port}[/green]")
            except Exception:
                console.print("[yellow]⚠️ Install streamlit: pip install streamlit[/yellow]")

        if ENABLE_PROFILING or show_timing:
            duration = time.perf_counter() - start
            console.print(f"[dim][Profiling] deploy.streamlit_app completed in {duration:.4f}s[/dim]")

        return save_path


    @staticmethod
    def show_options(show_timing: bool = False):
        if ENABLE_PROFILING or show_timing:
            start = time.perf_counter()

        table = Table(title="🚀 BizLens Deployment Options", show_lines=True)
        table.add_column("Platform", style="cyan")
        table.add_column("Function", style="green")
        table.add_row("Streamlit", "bl.deploy.streamlit_app(df)")
        table.add_row("Gradio", "bl.deploy.gradio_app(df)")
        console.print(table)

        if ENABLE_PROFILING or show_timing:
            duration = time.perf_counter() - start
            console.print(f"[dim][Profiling] deploy.show_options completed in {duration:.4f}s[/dim]")