"""
BizLens v2.2.2 — Deployment & Ecosystem Module

Deployment Options:
- Streamlit: Interactive analytics dashboards (bl.deploy.streamlit_app)
- Gradio: Quick ML demos and interfaces (bl.deploy.gradio_app)
- Panel: Complex dashboards and reports (bl.deploy.panel_app)
- FastAPI: REST API endpoints (bl.deploy.api)
- Voila: Jupyter notebook to web app (bl.deploy.voila)

PyPI Ecosystem:
- bl.packages.search(): Search PyPI for analytics packages
- bl.packages.ecosystem(): BizLens-compatible package recommendations
- bl.packages.install(): Install packages with pip programmatically
"""

import subprocess
import sys
import warnings
from typing import Optional, List, Dict, Any
import pandas as pd
from rich.console import Console
from rich.table import Table
from pathlib import Path

warnings.filterwarnings("ignore")
console = Console()


# ─────────────────────────────────────────────────────────────────────────────
# DEPLOYMENT OPTIONS
# ─────────────────────────────────────────────────────────────────────────────

class deploy:
    """
    Deploy BizLens analytics as interactive web applications.

    Supported platforms:
        - Streamlit (recommended for analytics dashboards)
        - Gradio (quick ML demos)
        - Panel (complex dashboards)
        - FastAPI (REST API)

    Example:
        >>> import bizlens as bl
        >>> import pandas as pd
        >>> df = bl.load_dataset('iris')
        >>> bl.deploy.streamlit_app(df, title="Iris Analysis")
    """

    @staticmethod
    def streamlit_app(
        data: Optional[pd.DataFrame] = None,
        title: str = "BizLens Analytics Dashboard",
        calculation_level: str = "sample",
        port: int = 8501,
        launch: bool = True,
        save_path: str = "bizlens_dashboard.py",
    ) -> str:
        """
        Generate and optionally launch a Streamlit analytics dashboard.

        Args:
            data: Optional DataFrame to pre-load (can also upload in UI)
            title: Dashboard title shown in browser
            calculation_level: 'sample' or 'population'
            port: Port to run Streamlit on (default 8501)
            launch: If True, launch the app immediately
            save_path: Where to save the generated app script

        Returns:
            Path to the generated Streamlit app file

        Example:
            >>> df = bl.load_dataset('titanic')
            >>> bl.deploy.streamlit_app(df, title="Titanic Analysis", port=8502)

        Installation:
            pip install streamlit
        """
        app_code = f'''"""
BizLens Analytics Dashboard
Generated by BizLens v2.2.2 — https://pypi.org/project/bizlens/
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import bizlens as bl
import io

st.set_page_config(
    page_title="{title}",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Header ───────────────────────────────────────────────────────────────
st.title("📊 {title}")
st.markdown("**Powered by [BizLens v2.2.2](https://pypi.org/project/bizlens/)** — Descriptive · Diagnostic · Predictive Analytics")
st.divider()

# ─── Sidebar ──────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("⚙️ Settings")
    calc_level = st.selectbox(
        "Calculation Level",
        ["sample", "population"],
        index=0,
        help="Sample uses n-1 (Bessel's correction); Population uses n"
    )
    color_scheme = st.selectbox("Color Scheme", ["academic", "pastel", "vibrant"])
    st.divider()

    st.header("📥 Data Source")
    data_source = st.radio(
        "Choose data source",
        ["Upload CSV", "Built-in Dataset", "Enter Manually"]
    )

    df = None
    if data_source == "Upload CSV":
        uploaded = st.file_uploader("Upload your CSV file", type=["csv", "xlsx"])
        if uploaded:
            if uploaded.name.endswith(".csv"):
                df = pd.read_csv(uploaded)
            else:
                df = pd.read_excel(uploaded)
    elif data_source == "Built-in Dataset":
        dataset_name = st.selectbox(
            "Choose dataset",
            ["iris", "titanic", "tips", "penguins", "diamonds", "flights", "mpg"]
        )
        df = bl.load_dataset(dataset_name, show_citation=False)
    else:
        st.info("Enter data manually below (main area)")

# ─── Main Content ──────────────────────────────────────────────────────────
if df is not None:
    tab1, tab2, tab3, tab4 = st.tabs(
        ["📊 Descriptive", "🔬 Diagnostic", "📈 Predictive", "📋 Raw Data"]
    )

    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
    cat_cols = df.select_dtypes(exclude=np.number).columns.tolist()

    # ── Tab 1: Descriptive ────────────────────────────────────────────────
    with tab1:
        st.subheader("📊 Descriptive Analytics")
        col1, col2 = st.columns([1, 1])

        with col1:
            st.metric("Rows", df.shape[0])
            st.metric("Columns", df.shape[1])
            st.metric("Missing Values", df.isnull().sum().sum())
            st.metric("Numeric Columns", len(numeric_cols))

        with col2:
            st.metric("Categorical Columns", len(cat_cols))
            st.metric("Duplicates", df.duplicated().sum())
            ddof = 1 if calc_level == "sample" else 0
            if numeric_cols:
                overall_std = df[numeric_cols].std(ddof=ddof).mean()
                st.metric(f"Avg Std Dev ({calc_level})", f"{{overall_std:.3f}}")

        st.divider()
        st.write("**Summary Statistics** (using", calc_level, "formula)")
        ddof = 1 if calc_level == "sample" else 0
        desc = df[numeric_cols].agg(["mean", "median", "std", "min", "max", "skew"])
        st.dataframe(desc.style.format("{{:.3f}}"), use_container_width=True)

        st.divider()
        if numeric_cols:
            selected_col = st.selectbox("Select column to analyze:", numeric_cols)
            col_data = df[selected_col].dropna()

            col_a, col_b = st.columns(2)
            with col_a:
                fig, ax = plt.subplots(figsize=(7, 4))
                ax.hist(col_data, bins="auto", color="#2E86AB", edgecolor="white", alpha=0.85)
                ax.axvline(col_data.mean(), color="#D62828", linestyle="--", label=f"Mean: {{col_data.mean():.2f}}")
                ax.axvline(col_data.median(), color="#A23B72", linestyle="-.", label=f"Median: {{col_data.median():.2f}}")
                ax.set_title(f"{{selected_col}} Distribution", fontweight="bold")
                ax.legend()
                st.pyplot(fig)
                plt.close()

            with col_b:
                fig, ax = plt.subplots(figsize=(7, 4))
                ax.boxplot(col_data, patch_artist=True,
                           boxprops=dict(facecolor="#2E86AB", alpha=0.7))
                ax.set_title(f"{{selected_col}} Boxplot", fontweight="bold")
                st.pyplot(fig)
                plt.close()

    # ── Tab 2: Diagnostic ─────────────────────────────────────────────────
    with tab2:
        st.subheader("🔬 Diagnostic Analytics")

        if len(numeric_cols) >= 2:
            st.write("**Correlation Matrix**")
            corr = df[numeric_cols].corr()
            fig, ax = plt.subplots(figsize=(10, 7))
            sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
                        center=0, ax=ax, linewidths=0.5)
            ax.set_title("Pearson Correlation Matrix", fontweight="bold")
            st.pyplot(fig)
            plt.close()

        if len(numeric_cols) >= 1 and len(cat_cols) >= 1:
            st.divider()
            st.write("**Group Comparison (t-test)**")
            num_col = st.selectbox("Numeric variable:", numeric_cols, key="ttest_num")
            cat_col = st.selectbox("Grouping variable:", cat_cols, key="ttest_cat")
            groups = df[cat_col].dropna().unique()[:2]

            if len(groups) >= 2:
                from scipy import stats
                g1 = df[df[cat_col] == groups[0]][num_col].dropna()
                g2 = df[df[cat_col] == groups[1]][num_col].dropna()
                t_stat, p_val = stats.ttest_ind(g1, g2)
                col1, col2, col3 = st.columns(3)
                col1.metric(f"{{groups[0]}} mean", f"{{g1.mean():.3f}}")
                col2.metric(f"{{groups[1]}} mean", f"{{g2.mean():.3f}}")
                col3.metric("p-value", f"{{p_val:.4f}}", delta="Significant" if p_val < 0.05 else "Not significant")
                if p_val < 0.05:
                    st.success(f"✅ Significant difference between {{groups[0]}} and {{groups[1]}} (p={p_val:.4f})")
                else:
                    st.info(f"ℹ️ No significant difference (p={p_val:.4f})")

    # ── Tab 3: Predictive ─────────────────────────────────────────────────
    with tab3:
        st.subheader("📈 Predictive Analytics")
        if len(numeric_cols) >= 2:
            from scipy.stats import linregress
            x_col = st.selectbox("Predictor (X):", numeric_cols, key="pred_x")
            y_col = st.selectbox("Target (Y):", numeric_cols, key="pred_y", index=min(1, len(numeric_cols)-1))

            if x_col != y_col:
                clean = df[[x_col, y_col]].dropna()
                x_data = clean[x_col].values
                y_data = clean[y_col].values
                slope, intercept, r_value, p_val, std_err = linregress(x_data, y_data)
                r_sq = r_value ** 2

                col1, col2, col3 = st.columns(3)
                col1.metric("R² (Explained Variance)", f"{{r_sq:.4f}}")
                col2.metric("p-value", f"{{p_val:.4f}}")
                col3.metric("Equation", f"ŷ={{intercept:.2f}} + {{slope:.2f}}x")

                fig, axes = plt.subplots(1, 2, figsize=(13, 5))
                axes[0].scatter(x_data, y_data, alpha=0.5, color="#2E86AB", s=30)
                x_sorted = np.sort(x_data)
                axes[0].plot(x_sorted, intercept + slope * x_sorted, color="#D62828", linewidth=2)
                axes[0].set_title(f"{{y_col}} ~ {{x_col}}  |  R²={{r_sq:.3f}}", fontweight="bold")
                axes[0].set_xlabel(x_col); axes[0].set_ylabel(y_col)

                residuals = y_data - (intercept + slope * x_data)
                axes[1].scatter(intercept + slope * x_data, residuals, alpha=0.5, color="#A23B72", s=30)
                axes[1].axhline(0, color="#D62828", linestyle="--")
                axes[1].set_title("Residual Plot", fontweight="bold")
                axes[1].set_xlabel("Fitted values"); axes[1].set_ylabel("Residuals")

                st.pyplot(fig)
                plt.close()

    # ── Tab 4: Raw Data ───────────────────────────────────────────────────
    with tab4:
        st.subheader("📋 Raw Data")
        st.dataframe(df, use_container_width=True)
        csv_data = df.to_csv(index=False).encode("utf-8")
        st.download_button("⬇️ Download CSV", csv_data, "bizlens_data.csv", "text/csv")

else:
    st.info("👈 Select a data source from the sidebar to begin analysis.")
    st.markdown("""
    ### Welcome to BizLens Analytics Dashboard!

    **How to use:**
    1. Select a data source in the sidebar (upload CSV, built-in dataset, or enter manually)
    2. Explore the **Descriptive**, **Diagnostic**, and **Predictive** tabs
    3. All statistics use your chosen calculation level (sample vs population)

    **Built-in datasets:** iris, titanic, tips, penguins, diamonds, flights, mpg

    **Powered by:** [BizLens](https://pypi.org/project/bizlens/) · NumPy · Pandas · SciPy · Matplotlib · Seaborn
    """)
'''

        # Save the app file
        Path(save_path).write_text(app_code)
        console.print(f"[green]✅ Streamlit app saved to: {save_path}[/green]")

        if launch:
            console.print(f"[bold]🚀 Launching Streamlit on port {port}...[/bold]")
            console.print(f"[dim]App will open at: http://localhost:{port}[/dim]")
            console.print("[dim]Press Ctrl+C to stop the server[/dim]")
            try:
                import streamlit
                subprocess.Popen([sys.executable, "-m", "streamlit", "run",
                                  save_path, "--server.port", str(port)])
                console.print(f"[green]✅ Dashboard running at http://localhost:{port}[/green]")
            except ImportError:
                console.print("[yellow]⚠️  Streamlit not installed. Install with:[/yellow]")
                console.print("    pip install streamlit")
                console.print(f"[dim]Then run: streamlit run {save_path}[/dim]")

        return save_path

    @staticmethod
    def gradio_app(
        data: Optional[pd.DataFrame] = None,
        title: str = "BizLens Analytics",
        launch: bool = True,
        port: int = 7860,
        save_path: str = "bizlens_gradio_app.py",
    ) -> str:
        """
        Generate a Gradio interface for BizLens analytics.

        Gradio is ideal for quick demos and sharing via public URLs.

        Installation:
            pip install gradio

        Example:
            >>> bl.deploy.gradio_app(df, title="My Analytics Demo", launch=True)
        """
        app_code = f'''"""BizLens Gradio App — Generated by BizLens v2.2.2"""
import gradio as gr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import bizlens as bl
from scipy.stats import linregress

def analyze(file, dataset_name, calc_level, column_name):
    if file is not None:
        df = pd.read_csv(file.name)
    elif dataset_name:
        df = bl.load_dataset(dataset_name, show_citation=False)
    else:
        return "Please upload a file or select a dataset.", None

    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
    if not numeric_cols:
        return "No numeric columns found.", None

    col = column_name if column_name in numeric_cols else numeric_cols[0]
    ddof = 1 if calc_level == "sample" else 0
    arr = df[col].dropna().values

    stats_text = f"""
📊 **{col}** — {calc_level.upper()} Statistics
n = {len(arr)}
Mean: {arr.mean():.4f}
Median: {np.median(arr):.4f}
Std Dev ({'n-1' if ddof==1 else 'n'}): {arr.std(ddof=ddof):.4f}
Min / Max: {arr.min():.4f} / {arr.max():.4f}
Skewness: {float(__import__('scipy').stats.skew(arr)):.4f}
"""
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(arr, bins="auto", color="#2E86AB", edgecolor="white", alpha=0.85)
    ax.axvline(arr.mean(), color="#D62828", linestyle="--", label=f"Mean: {{arr.mean():.2f}}")
    ax.axvline(np.median(arr), color="#A23B72", linestyle="-.", label=f"Median: {{np.median(arr):.2f}}")
    ax.legend()
    ax.set_title(f"{{col}} Distribution [{calc_level}]", fontweight="bold")
    plt.tight_layout()
    return stats_text, fig

with gr.Blocks(title="{title}") as demo:
    gr.Markdown("# 📊 {title}\\nPowered by **BizLens v2.2.2**")
    with gr.Row():
        file_input = gr.File(label="Upload CSV", file_types=[".csv"])
        dataset_select = gr.Dropdown(
            choices=["iris", "titanic", "tips", "penguins", "mpg", "flights"],
            label="Or select built-in dataset"
        )
        calc_level = gr.Dropdown(choices=["sample", "population"], value="sample", label="Calculation Level")
        col_name = gr.Textbox(label="Column name (leave blank for auto)")
    btn = gr.Button("🔍 Analyze", variant="primary")
    with gr.Row():
        stats_out = gr.Markdown()
        plot_out = gr.Plot()
    btn.click(analyze, inputs=[file_input, dataset_select, calc_level, col_name], outputs=[stats_out, plot_out])

if __name__ == "__main__":
    demo.launch(server_port={port}, share=False)
'''
        Path(save_path).write_text(app_code)
        console.print(f"[green]✅ Gradio app saved to: {save_path}[/green]")
        if launch:
            try:
                import gradio
                subprocess.Popen([sys.executable, save_path])
                console.print(f"[green]✅ Gradio app running at http://localhost:{port}[/green]")
            except ImportError:
                console.print("[yellow]⚠️  Install gradio: pip install gradio[/yellow]")
                console.print(f"[dim]Then run: python {save_path}[/dim]")
        return save_path

    @staticmethod
    def show_options() -> None:
        """Show all available deployment options with installation commands."""
        table = Table(title="🚀 BizLens Deployment Options", show_lines=True)
        table.add_column("Platform", style="cyan", width=12)
        table.add_column("Best For", width=28)
        table.add_column("Function", style="green", width=28)
        table.add_column("Install", style="dim", width=22)

        options = [
            ("Streamlit", "Analytics dashboards & reports", "bl.deploy.streamlit_app(df)", "pip install streamlit"),
            ("Gradio", "Quick demos, shareable links", "bl.deploy.gradio_app(df)", "pip install gradio"),
            ("Panel", "Complex layouts & widgets", "bl.deploy.panel_app(df)", "pip install panel"),
            ("FastAPI", "REST API for analytics", "bl.deploy.api(df)", "pip install fastapi uvicorn"),
            ("Voila", "Jupyter notebook → web", "bl.deploy.voila()", "pip install voila"),
            ("Shiny", "R-style reactive apps", "bl.deploy.shiny_app(df)", "pip install shiny"),
        ]
        for row in options:
            table.add_row(*row)
        console.print(table)
        console.print("\n[bold]Quick start:[/bold]")
        console.print("  >>> import bizlens as bl")
        console.print("  >>> df = bl.load_dataset('iris')")
        console.print("  >>> bl.deploy.streamlit_app(df)   # Opens at http://localhost:8501")
        console.print("  >>> bl.deploy.gradio_app(df)      # Opens at http://localhost:7860")


# ─────────────────────────────────────────────────────────────────────────────
# PYPI PACKAGE ECOSYSTEM
# ─────────────────────────────────────────────────────────────────────────────

# Curated ecosystem by category
BIZLENS_ECOSYSTEM: Dict[str, List[Dict]] = {
    "Core Analytics": [
        {"name": "bizlens", "pypi": "bizlens", "desc": "This package — integrated analytics platform", "install": "pip install bizlens"},
        {"name": "NumPy", "pypi": "numpy", "desc": "Numerical computing foundation", "install": "pip install numpy"},
        {"name": "Pandas", "pypi": "pandas", "desc": "DataFrame manipulation and analysis", "install": "pip install pandas"},
        {"name": "Polars", "pypi": "polars", "desc": "Fast DataFrame library (Rust-powered)", "install": "pip install polars"},
        {"name": "SciPy", "pypi": "scipy", "desc": "Scientific computing, statistics, optimization", "install": "pip install scipy"},
    ],
    "Visualization": [
        {"name": "Matplotlib", "pypi": "matplotlib", "desc": "Core plotting library", "install": "pip install matplotlib"},
        {"name": "Seaborn", "pypi": "seaborn", "desc": "Statistical data visualization", "install": "pip install seaborn"},
        {"name": "Plotly", "pypi": "plotly", "desc": "Interactive charts and dashboards", "install": "pip install plotly"},
        {"name": "Altair", "pypi": "altair", "desc": "Declarative statistical visualization", "install": "pip install altair"},
        {"name": "Bokeh", "pypi": "bokeh", "desc": "Interactive browser visualizations", "install": "pip install bokeh"},
    ],
    "Machine Learning": [
        {"name": "Scikit-Learn", "pypi": "scikit-learn", "desc": "Classical ML algorithms", "install": "pip install scikit-learn"},
        {"name": "Statsmodels", "pypi": "statsmodels", "desc": "Statistical models and tests", "install": "pip install statsmodels"},
        {"name": "XGBoost", "pypi": "xgboost", "desc": "Gradient boosted trees", "install": "pip install xgboost"},
        {"name": "LightGBM", "pypi": "lightgbm", "desc": "Fast gradient boosting", "install": "pip install lightgbm"},
        {"name": "CatBoost", "pypi": "catboost", "desc": "Categorical feature boosting", "install": "pip install catboost"},
    ],
    "Deep Learning": [
        {"name": "TensorFlow", "pypi": "tensorflow", "desc": "Deep learning framework (Google)", "install": "pip install tensorflow"},
        {"name": "PyTorch", "pypi": "torch", "desc": "Deep learning framework (Meta)", "install": "pip install torch"},
        {"name": "Keras", "pypi": "keras", "desc": "High-level deep learning API", "install": "pip install keras"},
    ],
    "Optimization": [
        {"name": "PuLP", "pypi": "PuLP", "desc": "Linear programming (included in BizLens)", "install": "pip install PuLP"},
        {"name": "Pyomo", "pypi": "pyomo", "desc": "Algebraic modeling for optimization", "install": "pip install pyomo"},
        {"name": "OR-Tools", "pypi": "ortools", "desc": "Google operations research tools", "install": "pip install ortools"},
        {"name": "CVXPY", "pypi": "cvxpy", "desc": "Convex optimization", "install": "pip install cvxpy"},
        {"name": "SciPy Optimize", "pypi": "scipy", "desc": "Optimization algorithms in SciPy", "install": "pip install scipy"},
    ],
    "Time Series": [
        {"name": "Prophet", "pypi": "prophet", "desc": "Facebook time series forecasting", "install": "pip install prophet"},
        {"name": "statsforecast", "pypi": "statsforecast", "desc": "Fast statistical forecasting", "install": "pip install statsforecast"},
        {"name": "tslearn", "pypi": "tslearn", "desc": "Time series ML toolkit", "install": "pip install tslearn"},
        {"name": "sktime", "pypi": "sktime", "desc": "Unified time series framework", "install": "pip install sktime"},
    ],
    "Deployment": [
        {"name": "Streamlit", "pypi": "streamlit", "desc": "Analytics dashboards (recommended)", "install": "pip install streamlit"},
        {"name": "Gradio", "pypi": "gradio", "desc": "Quick ML demos, shareable links", "install": "pip install gradio"},
        {"name": "Panel", "pypi": "panel", "desc": "Complex multi-page dashboards", "install": "pip install panel"},
        {"name": "FastAPI", "pypi": "fastapi", "desc": "High-performance REST APIs", "install": "pip install fastapi uvicorn"},
        {"name": "Voila", "pypi": "voila", "desc": "Jupyter notebooks to web apps", "install": "pip install voila"},
    ],
    "Data Sources": [
        {"name": "Kaggle", "pypi": "kaggle", "desc": "Access 50,000+ datasets from Kaggle", "install": "pip install kaggle"},
        {"name": "OpenML", "pypi": "openml", "desc": "Free ML datasets (no credentials)", "install": "pip install openml"},
        {"name": "wbgapi", "pypi": "wbgapi", "desc": "World Bank economic data", "install": "pip install wbgapi"},
        {"name": "yfinance", "pypi": "yfinance", "desc": "Yahoo Finance stock/market data", "install": "pip install yfinance"},
        {"name": "pandas-datareader", "pypi": "pandas-datareader", "desc": "FRED, World Bank, OECD data", "install": "pip install pandas-datareader"},
    ],
    "Explainability": [
        {"name": "SHAP", "pypi": "shap", "desc": "Model explanation via Shapley values", "install": "pip install shap"},
        {"name": "LIME", "pypi": "lime", "desc": "Local model interpretability", "install": "pip install lime"},
        {"name": "eli5", "pypi": "eli5", "desc": "Debug and explain ML models", "install": "pip install eli5"},
    ],
    "Notebooks & Reports": [
        {"name": "JupyterLab", "pypi": "jupyterlab", "desc": "Interactive notebook environment", "install": "pip install jupyterlab"},
        {"name": "nbconvert", "pypi": "nbconvert", "desc": "Convert notebooks to HTML/PDF", "install": "pip install nbconvert"},
        {"name": "Quarto", "pypi": "quarto", "desc": "Scientific publishing system", "install": "pip install quarto"},
        {"name": "Rich", "pypi": "rich", "desc": "Beautiful terminal output (included)", "install": "pip install rich"},
    ],
}


class packages:
    """
    Discover and manage the BizLens analytics ecosystem.

    Example:
        >>> bl.packages.ecosystem()              # Full curated list
        >>> bl.packages.search('optimization')   # Search by category
        >>> bl.packages.search_pypi('timeseries') # Live PyPI search
        >>> bl.packages.install('plotly')         # Install a package
    """

    @staticmethod
    def ecosystem(category: Optional[str] = None) -> pd.DataFrame:
        """
        Show the full BizLens-compatible package ecosystem.

        Args:
            category: Filter by category (e.g. 'optimization', 'visualization')
                      Leave None to show all categories

        Returns:
            DataFrame of packages with name, description, install command

        Example:
            >>> bl.packages.ecosystem()
            >>> bl.packages.ecosystem('Machine Learning')
        """
        categories = BIZLENS_ECOSYSTEM

        if category:
            # Case-insensitive partial match
            matched = {k: v for k, v in categories.items()
                       if category.lower() in k.lower()}
            if not matched:
                available = list(categories.keys())
                console.print(f"[yellow]Category '{category}' not found.[/yellow]")
                console.print(f"Available: {', '.join(available)}")
                return pd.DataFrame()
            categories = matched

        all_rows = []
        for cat, pkgs in categories.items():
            console.print(f"\n[bold cyan]📦 {cat}[/bold cyan]")
            table = Table(show_lines=False, show_header=True)
            table.add_column("Package", style="green", width=16)
            table.add_column("Description", width=42)
            table.add_column("Install", style="dim", width=28)
            for pkg in pkgs:
                table.add_row(pkg["name"], pkg["desc"], pkg["install"])
                all_rows.append({"Category": cat, **pkg})
            console.print(table)

        return pd.DataFrame(all_rows)

    @staticmethod
    def search(keyword: str) -> pd.DataFrame:
        """
        Search the curated ecosystem by keyword.

        Args:
            keyword: Search term (searches name, description, category)

        Returns:
            Matching packages DataFrame

        Example:
            >>> bl.packages.search('time series')
            >>> bl.packages.search('classification')
            >>> bl.packages.search('deploy')
        """
        kw = keyword.lower()
        results = []
        for cat, pkgs in BIZLENS_ECOSYSTEM.items():
            for pkg in pkgs:
                if (kw in pkg["name"].lower() or
                        kw in pkg["desc"].lower() or
                        kw in cat.lower()):
                    results.append({"Category": cat, **pkg})

        if not results:
            console.print(f"[yellow]No packages found matching '{keyword}'[/yellow]")
            console.print("Try: 'ml', 'optimization', 'visualization', 'deployment', 'timeseries'")
            return pd.DataFrame()

        df = pd.DataFrame(results)
        table = Table(title=f"🔍 Packages matching '{keyword}'", show_lines=True)
        table.add_column("Category", style="cyan", width=14)
        table.add_column("Package", style="green", width=14)
        table.add_column("Description", width=38)
        table.add_column("Install", style="dim", width=24)
        for _, row in df.iterrows():
            table.add_row(row["Category"], row["name"], row["desc"], row["install"])
        console.print(table)
        return df

    @staticmethod
    def search_pypi(query: str, limit: int = 10) -> pd.DataFrame:
        """
        Search PyPI (Python Package Index) for packages by keyword.

        Args:
            query: Search term
            limit: Max results to return (default 10)

        Returns:
            DataFrame with package names, descriptions, and links

        Example:
            >>> bl.packages.search_pypi('analytics')
            >>> bl.packages.search_pypi('optimization')
            >>> bl.packages.search_pypi('forecasting')
        """
        try:
            import urllib.request
            import json
            url = f"https://pypi.org/pypi/{query}/json"
            # Try direct package info first
            try:
                with urllib.request.urlopen(url, timeout=5) as resp:
                    data = json.loads(resp.read())
                info = data["info"]
                df = pd.DataFrame([{
                    "Name": info["name"],
                    "Version": info["version"],
                    "Description": info["summary"],
                    "Author": info["author"],
                    "PyPI URL": f"https://pypi.org/project/{info['name']}/",
                }])
                console.print(f"[bold]📦 PyPI Package: {info['name']} v{info['version']}[/bold]")
                console.print(f"[dim]{info['summary']}[/dim]")
                console.print(f"[dim]Install: pip install {info['name']}[/dim]")
                return df
            except Exception:
                pass

            # Fallback: show ecosystem search
            console.print(f"[dim]Showing BizLens ecosystem packages matching '{query}'[/dim]")
            return packages.search(query)

        except Exception as e:
            console.print(f"[yellow]PyPI search unavailable: {e}[/yellow]")
            return packages.search(query)

    @staticmethod
    def install(package_name: str, confirm: bool = True) -> bool:
        """
        Install a package using pip.

        Args:
            package_name: Package name to install
            confirm: Ask for confirmation before installing (default True)

        Returns:
            True if installation succeeded

        Example:
            >>> bl.packages.install('plotly')
            >>> bl.packages.install('streamlit')
        """
        if confirm:
            console.print(f"[bold yellow]⚠️  About to install: {package_name}[/bold yellow]")
            response = input("Confirm? (y/n): ").strip().lower()
            if response != "y":
                console.print("[dim]Installation cancelled.[/dim]")
                return False

        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", package_name],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            console.print(f"[green]✅ Successfully installed {package_name}[/green]")
            return True
        else:
            console.print(f"[red]❌ Installation failed: {result.stderr}[/red]")
            return False

    @staticmethod
    def check_installed() -> pd.DataFrame:
        """
        Check which BizLens ecosystem packages are installed.

        Returns:
            DataFrame showing installed status for all ecosystem packages

        Example:
            >>> bl.packages.check_installed()
        """
        import importlib.util
        all_pkgs = set()
        for pkgs in BIZLENS_ECOSYSTEM.values():
            for pkg in pkgs:
                all_pkgs.add((pkg["name"], pkg["pypi"]))

        results = []
        for name, pypi_name in sorted(all_pkgs):
            import_name = pypi_name.replace("-", "_").lower()
            installed = importlib.util.find_spec(import_name) is not None
            results.append({
                "Package": name,
                "PyPI Name": pypi_name,
                "Installed": "✅" if installed else "❌",
            })

        df = pd.DataFrame(results)
        installed_count = df["Installed"].eq("✅").sum()
        table = Table(title=f"📦 Ecosystem Status ({installed_count}/{len(df)} installed)", show_lines=True)
        table.add_column("Package", style="cyan", width=16)
        table.add_column("PyPI Name", style="dim", width=20)
        table.add_column("Installed", justify="center", width=10)
        for _, row in df.iterrows():
            table.add_row(row["Package"], row["PyPI Name"], row["Installed"])
        console.print(table)
        return df
